title: "Monty\'s"
tagline: "Monty Dickerson"
description: "Monty Dickerson is a front-end software developer specializing in javascript."
url: http://montydickerson.com
baseurl: "/"
type: "website"
favicon: "images/favicon/js.png"
image144: "images/monty/sq144.jpg"

author:
  name: "Monty Dickerson"
  twitter: "puresight"
  github: "puresight"
  linkedin: "montydickerson"

defaults:
  -
    scope:
      path: ""
    values:
      image:
        url: "images/monty/sq200.jpg"
        width: 200
        height: 200
      description: "Monty Dickerson is a front-end software developer specializing in javascript."
      creator: "Monty Dickerson"
      publisher: "Monty Dickerson"
#
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
#
